import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { calculateWeeklySales } from "@/lib/weekly-sales";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
type Sale = { closingDate: string; value: string | number; internalStatus: string; campaignId?: number | null };

export function ActiveWeeklyChart({ records, month, weeklyGoal, title }: { records: Sale[]; month: string; weeklyGoal?: number | null; title: string }) {
  if (!month) return <Card className="border-[#d8e5eb] bg-white"><CardContent className="p-5 text-sm text-[#617782]">Selecione um mês para acompanhar as cinco semanas.</CardContent></Card>;
  const weeks = calculateWeeklySales(records.filter(record => record.internalStatus === "closed"), month);
  const maximum = Math.max(...weeks.map(week => week.total), weeklyGoal ?? 0, 1);
  return <Card className="border-[#d8e5eb] bg-white shadow-sm"><CardHeader><CardTitle className="text-lg text-[#174f6f]">{title}</CardTitle><p className="text-xs text-[#6e7f88]">S1–S5 · somente fechamentos deste módulo. {weeklyGoal ? `Meta semanal: ${money.format(weeklyGoal)}.` : "Meta semanal ainda não definida."}</p></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{weeks.map(week => { const progress = weeklyGoal ? Math.min(100, week.total / weeklyGoal * 100) : 0; return <div key={week.week} className="min-w-0 rounded-xl border border-[#dce8ed] bg-[#f7fafb] p-3"><div className="text-center text-xs font-semibold text-[#174f6f]">{week.label} <span className="font-normal text-[#7d8d95]">{week.period}</span></div><div className="mt-2 flex h-24 items-end overflow-hidden rounded-lg bg-[#e4eef2]"><div className="w-full rounded-t-md bg-[#2e7da3]" style={{ height: `${week.total > 0 ? Math.max(5, week.total / maximum * 100) : 0}%` }} /></div><p className="mt-2 text-center text-sm font-bold text-[#174f6f]">{money.format(week.total)}</p><p className="text-center text-[11px] text-[#7d8d95]">{week.count} venda{week.count === 1 ? "" : "s"}</p>{weeklyGoal ? <p className={`mt-2 rounded-md p-1 text-center text-[11px] font-semibold ${week.total >= weeklyGoal ? "bg-[#e9f7eb] text-[#2f7b40]" : "bg-[#fff7df] text-[#9a6b12]"}`}>{week.total >= weeklyGoal ? `+${money.format(week.total - weeklyGoal)}` : `Faltam ${money.format(weeklyGoal - week.total)}`}</p> : <p className="mt-2 text-center text-[11px] text-[#8b989d]">Sem meta</p>}{weeklyGoal ? <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#d8e5eb]"><div className="h-full bg-[#cbb548]" style={{ width: `${progress}%` }} /></div> : null}</div>; })}</div></CardContent></Card>;
}

export function ActiveCampaignChart({ records, campaigns }: { records: Sale[]; campaigns: Array<{ id: number; name: string }> }) {
  const totals = campaigns.map(campaign => ({ campaign, total: records.filter(record => record.internalStatus === "closed" && record.campaignId === campaign.id).reduce((sum, record) => sum + Number(record.value), 0) }));
  const maximum = Math.max(1, ...totals.map(row => row.total));
  return <Card className="border-[#d8e5eb] bg-white shadow-sm"><CardHeader><CardTitle className="text-lg text-[#174f6f]">Valor gerado por campanha · Pacientes Ativos</CardTitle><p className="text-xs text-[#6e7f88]">Cada campanha cadastrada cria automaticamente sua própria coluna. Os dados do Funil de Vendas não entram aqui.</p></CardHeader><CardContent>{totals.length ? <div className="overflow-x-auto"><div className="flex min-w-max gap-3 pb-2">{totals.map(row => <div key={row.campaign.id} className="w-32 rounded-xl border border-[#dce8ed] bg-[#f7fafb] p-3 text-center"><p className="text-sm font-bold text-[#174f6f]">{money.format(row.total)}</p><div className="mt-3 flex h-28 items-end overflow-hidden rounded-lg bg-[#e4eef2]"><div className="w-full rounded-t-md bg-[#4a9eb2]" style={{ height: `${row.total ? Math.max(5, row.total / maximum * 100) : 0}%` }} /></div><p className="mt-2 line-clamp-2 min-h-9 text-xs font-semibold text-[#486a7b]" title={row.campaign.name}>{row.campaign.name}</p></div>)}</div></div> : <p className="rounded-xl bg-[#f7fafb] p-8 text-center text-sm text-[#6e7f88]">Cadastre a primeira campanha desta página para iniciar o gráfico.</p>}</CardContent></Card>;
}
